server:
  port: 8001

spring:
  #devtools
  devtools:
    restart:
      enabled: true  #设置开启热部署
    livereload:
      port: 35730
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  application:
    name: cloud-payment-service8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.55.97:3306/test_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

mybatis:
  mapperLocations: classpath:mapperxml/*.xml
  type-aliases-package: com.ink.springcloud.domain
