server:
  port: 1004
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
